############################# 访问路径、端口tomcat start #############################
server:
  # 项目端口
  port: 9091
  # 内嵌Tomcat
  tomcat:
    # tomcat编码
    uri-encoding: UTF-8
    threads:
      # tomcat线程池大小设置
      max: 1000
      # tomcat初始化线程数量
      min-spare: 30
  servlet:
    # HTTP编码
    encoding:
      charset: UTF-8
      enabled: true
      force: true
############################# 访问路径、端口tomcat end ###############################

################################ spring config start ###############################
spring:
  application:
    # 应用程序名称
    name: dice
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  # 当前项目maven激活环境
  profiles:
    active: @profileActive@
################################ spring config end #################################

mybatis-plus:
  typeEnumsPackage: com.bihell.dice.blog.enums
  global-config:
    db-config:
      id-type: auto
      logic-not-delete-value: 0
      logic-delete-value: 1
  mapper-locations: classpath:/mapper/*Mapper.xml
